name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pipeline:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
  playwright:
    needs: [pipeline]
    uses: ./.github/workflows/playwright.yml
  deploy:
    needs: [playwright]
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

        
