name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pipeline:
    uses: ./.github/workflows/pipeline.yml
  playwright:
    uses: ./.github/workflows/playwright.yml
  deploy:
    needs: [pipeline, playwright]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      render_deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        
