name: Deployment
on:
  workflow_call:
    inputs:
        render_deploy_url:
          required: true
          type: string

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Trigger Deploy
        env:
          deploy_url: ${{ inputs.RENDER_DEPLOY_HOOK }}
        run: |
          curl "$deploy_url"