name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@v1.8.0
        with:
          serviceId: https://full-stack-open-pokedex-l9gx.onrender.com
          apiKey: rnd_RQYfcpUd3oeT9geLVscwUNm74fkR
          multipleDeployment: false
